---
title: "Indicadores de acessibilidade"
author: "Ipea"
date: "27 de março de 2019"
output: github_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = "UTF-8", output_dir = "reports") })
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE, eval = FALSE)


library(knitr)
library(readr)
library(tidyverse)
library(dplyr)
library(readxl)
library(scales)
library(sf)
library(mapview)
library(data.table)
library(opentripplanner)
library(purrr)
library(httr)
library(furrr)

```

# Indicador de acesso cumulativo a oportunidades

Com a quantidade de oportunidades (saúde, educação, empregos) e a matriz de tempo de viagem calculada entre os hexágonos, é hora da etapa de calcular o indicador de acessibilidade. Como projeto piloto, será calculado o indicador para a cidade de Fortaleza:

```{r acess acumulativa}

# abrir matriz
matriz_fortaleza <- read_csv("../data/output_ttmatrix/traveltime_matrix_fortaleza_python.csv") %>%
  select(origin, destination, travel_time) %>%
  mutate(travel_time = travel_time/60)

# abrir oportunidades com hexagonos
hexagonos_fortaleza <- read_rds("../data/hex_agregados/hex_agregado_for.rds")

# quantas oportunidades de escolas podem ser acessadas em menos de 20 minutos?

access_ac_for <- hexagonos_fortaleza %>%
  left_join(matriz_fortaleza, by = c("id_hex" = "origin"))
  group_by(id_hex) %>%
  filter(travel_time < 20) %>%
  summarise_at(vars(saude_total, escolas_total), sum)


mapview(access_ac_for, zcol = "total_saude")



```


