---
title: "Untitled"
author: "Ipea"
date: "08/07/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("R/fun/setup.R")

```



```{r}
####### 3 Compute Income Deciles based on household income per capita --------------------

# cidade <- "for"
# res <- "09"

calcular_quintil <- function(cidade, res = "09") {
  
  # Pegar arquivo com os hexagonos com as atividades
  dir_hex <- sprintf("../data/hex_agregados/hex_agregado_%s_%s.rds", cidade, res)
  
  # abrir oportunidades com hexagonos
  hexagonos_sf <- read_rds(dir_hex) %>%
    filter(pop_total != 0) %>%
    ungroup()
  
  # calcular income per capta
  setDT(hexagonos_sf)[, renda_capta := renda_total/pop_total]
  
  summary(hexagonos_sf$renda_capta)
  boxplot(hexagonos_sf$renda_capta)
  
  # calcular quintis ponderados pela populacao
  quantiles  <- Hmisc::wtd.quantile(hexagonos_sf$renda_capta, weights=hexagonos_sf$pop_total, 
                                     probs=c( seq(0 , 1 , 0.1) ), 
                            type=c('quantile','(i-1)/(n-1)','i/(n+1)','i/n'), 
                            normwt=FALSE, na.rm=T)
  
  barplot(quantiles)
  quantiles
  
  # criar variaveis no df original
  setDT(hexagonos_sf)[, quintil := 1+ findInterval(renda_capta , quantiles[ -length(quantiles) ] ) ]
  
  
  
  # salvar
  path_out <- sprintf("../data/hex_agregado_quintil/hex_agregado_quintil_%s.rds", cidade)
  
  write_rds(hexagonos_sf %>% st_sf(), path_out)
  
}

# aplicar
calcular_quintil("for")


```

Agora fazer o boxplot:

```{r boxplot}

cidade <- "for"

boxplot_travel_times <- function(cidade) {
  
  # abrir acessibilidade
  path_acess <- sprintf("../data/output_access/acess_%s.rds", cidade)
  acess <- read_rds(path_acess) %>% st_set_geometry(NULL)
  
  # Pegar arquivo com os hexagonos com as atividades
  dir_hex <- sprintf("../data/hex_agregado_quintil/hex_agregado_quintil_%s.rds", cidade)
  
  # abrir oportunidades com hexagonos
  hexagonos_sf <- read_rds(dir_hex) %>%
    st_set_geometry(NULL) %>%
    select(id_hex, pop_total, quintil) %>%
    ungroup()
  
  # trazer a informacoa da renda para o hexagono na base da acessibilidade
  acess_quintil <- merge(setDT(acess), setDT(hexagonos_sf), 
                         by.x = "origin",
                         by.y = "id_hex",
                         all.x = TRUE)
                         
  # tirar populacao zero
  acess_quintil <- acess_quintil[pop_total > 0]
  
  # BOXPLOT ----------------------------------------------------------------------------------------
  
  # para transit, saude trabalho
  indicador <- "CMA"
  atividade <- "TT"
  modo <- "transit"
  
  title <- bquote("Distribuição da acessibilidade por"~bold(.("transporte público"))~"à"~bold(.("oportunidades de trabalho")))
  
    baseplot2 <- theme_minimal(base_family = "Roboto Condensed") +
    theme( 
      axis.text.y  = element_text(face="bold")
      # ,axis.text.x  = element_text(face="bold")
      ,panel.grid.minor = element_blank()
      ,strip.text = element_text(size = 8, face ="bold")
      ,legend.text = element_text(size = 8)
      , legend.position = "top"
      , axis.title = element_text(size = 8)
      , axis.text.x = element_blank()
      , title = element_text(size = 9)
      , plot.margin=unit(c(2,0,0,0),"mm")
      , axis.ticks.x = element_blank()
      , axis.line.x = element_blank()
    )
  
  acess_quintil %>%
    # Filtrar modo
    filter(mode == "transit") %>%
    # Filtrar indicador
    select(matches(indicador), origin, quintil, pop_total) %>%
    # Filtrar atividade
    select(matches(atividade), origin, quintil, pop_total) %>%
    # Wide to long
    gather(threshold, acess_abs, CMA_TT_15:CMA_TT_90) %>%
    mutate(threshold1 = as.integer(str_extract(threshold, "\\d+$"))) %>%
    # Refactor quintil
    mutate(quintil1 = quintil - 1) %>%
    # Pegar somente esses threshoold
    filter(threshold1 %in% c(30, 60, 90)) %>%
    mutate(threshold_name = paste0(str_extract(threshold, "\\d+$"), " minutos")) %>%
    mutate(threshold_name = forcats::fct_reorder(factor(threshold_name), threshold1)) %>%
    ggplot()+
    geom_boxplot(aes(x = factor(quintil), y = acess_abs, color = factor(quintil1)), 
                 outlier.colour=rgb(.5,.5,.5, alpha=0.2))+
    facet_grid(threshold_name ~ ., scales = "free_y")+
    scale_color_brewer(palette = "RdBu")+
    # hrbrthemes::theme_ipsum_rc() +
    labs(color = "Decil de renda",
         x = "",
         y = "Quantidade de oportunidades acessíveis",
         title = title) + 
    guides(color=guide_legend(nrow=1)) +
    baseplot2
  
}

ggsave("figure/boxplots_decil/for_CMA_P_transit_TT.png", dpi = 300, height = 10, width = 16, units = "cm")

```

