---
title: "Projeto Acesso a Oportunidades"
author: "Ipea"
date: "25 de abril de 2019"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE, eval = TRUE))

library(knitr)
library(readr)
library(dplyr)
# library(readxl)
library(scales)
library(sf)
# library(mapview)
library(data.table)
# library(h3jsr)
library(stringr)
library(purrr)
# library(furrr)
library(kableExtra)

library(tint)

source("R/sfc_as_cols.R")

`%nin%` = Negate(`%in%`)
```

## Quantidade de pontos origem-destino a serem analisados

```{r tirar pontos}

tirar_pontos <- function(hex_agregados) {
  
  vai <- read_rds(hex_agregados)
  
  vai_pop <- vai %>%
    filter(pop_total == 0)
  
  vai_atividade <- vai %>%
    filter(saude_total == 0 & escolas_total == 0 & empregos_total == 0)
  
  # Construir matriz
  
  for_od <- vai %>%
    tidyr::expand(id_hex, id_hex) %>%
    rename(origem = id_hex, destino = id_hex1)
  
  # Fazer limpeza
  for_od_v1 <- for_od %>%
    # Tirar origem == destino
    filter(origem != destino) %>%
    # Tirar hexagonos sem populacao
    filter(origem %nin% vai_pop$id_hex) %>%
    # Tirar hexagonos sem atividade
    filter(destino %nin% vai_atividade$id_hex)
  
  # Extrair numero de colunas
  
  fim <- nrow(for_od_v1)
    
}

```

Para a resolução 7 (2510 metros):

```{r aplicar 07}

files07 <- dir("../data/hex_agregados/", pattern = "_07.rds$", full.names = TRUE)

opa07 <- map_dbl(files07, tirar_pontos)

names(opa07) <- c("Belo Horizonte", "Curitiba", "Fortaleza", "Porto Alegre", "Recife", "Rio de Janeiro", "Sao Paulo")

# vai <- rbindlist(opa, idcol = "cidade_res")
# 
# vai_v1 <- vai %>%
#   count(cidade_res)

vai07 <- tibble::enframe(opa07)

write.table(vai07, "clipboard", sep="\t")


```


```{r tabela 08, cache = TRUE, caption = "Quantidade de pontos de consulta para a resolução de 960 metros"}

kable(vai) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```


Para a resolução 8 (960 metros):

```{r aplicar}

files <- dir("../data/hex_agregados/", pattern = "_08.rds$", full.names = TRUE)

opa <- map_dbl(files, tirar_pontos)

names(opa) <- c("Belo Horizonte", "Curitiba", "Fortaleza", "Porto Alegre", "Recife", "Rio de Janeiro", "Sao Paulo")

# vai <- rbindlist(opa, idcol = "cidade_res")
# 
# vai_v1 <- vai %>%
#   count(cidade_res)

vai <- tibble::enframe(opa)

write.table(vai, "clipboard", sep="\t")


```


```{r tabela 08, cache = TRUE, caption = "Quantidade de pontos de consulta para a resolução de 960 metros"}

kable(vai) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```


Aplicar para a resolução 9 (357 metros):

```{r aplicar 09, cache = TRUE}

files_09 <- dir("../data/hex_agregados/", pattern = "_09.rds$", full.names = TRUE)

opa_09 <- map_dbl(files_09, tirar_pontos)

names(opa_09) <- c("Belo Horizonte", "Curitiba", "Fortaleza", "Porto Alegre", "Recife", "Rio de Janeiro", "Sao Paulo")

# vai_09 <- rbindlist(opa, idcol = "cidade_res")
# 
# vai_09_v1 <- vai %>%
#   count(cidade_res)

vai_09 <- tibble::enframe(opa_09)

write.table(vai_09, "clipboard", sep="\t")

```


```{r tabela 09, cache = TRUE, caption = "Quantidade de pontos de consulta para a resolução de 357 metros", eval = FALSE}

kableExtra::kable(vai_09) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```
